### ISSUE TITLE
Define kstart.service in systemctl, but start failed for time-out reason

### ISSUE THREAD

**Issue by xiaominyan88** [rra/kstart#7] opened 2022-05-07 03:34 UTC
I install kstart through yum repo, and define a file "kstart.service" in the path /usr/lib/systemd/system/, the contents of kstart.service  are as follows:
```
[Unit]
Description=k5start service for Administration
Wants=network-online.target
After=syslog.target network.target network-online.target

[Service]
Type=forking
ExecStart=/usr/bin/k5start -U -f /etc/krb5.keytab -K 10 -l 24h
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
```
However, when I use systemctl start kstart to start kstart service, it always fail for the reason of time out , could you give me some advise?

**Comment by rra** [comment] 2022-06-29 18:12
The problem is the `Type=forking` line, which you don't need or want. You want `Type=exec` (at least until I add support for `sd_notify`, at which point you will want `Type=notify`.

I'm fairly sure this is the problem, so closing the issue, but feel free to re-open if that doesn't fix it.

**Closed as completed by rra** 2022-06-29 18:12 UTC
